### ISSUE TITLE
com.company.mySdlApplication.SdlRouterService-> .SdlRouterService

### ISSUE THREAD

**Issue by matwszedybyl** [smartdevicelink/sdl_android_guides#32]
In the Getting Started Guide...

Do we need to define the whole path of the SdlRouterService if the android manifest is in the same package as the SdlRouterService?  

 service
            android:name="com.company.mySdlApplication.SdlRouterService"
            android:exported="true" 
            android:process="com.smartdevicelink.router"

**Comment by askirk** [comment]
We don't, but this does make it clear to a developer what file we're talking about

**Comment by joeygrover** [comment]
It is a best practice thing to ensure the exact file is being correctly stated in the manifest.
