### ISSUE TITLE
Remove 'SmartDeviceLink Service' section in the Upgrading to Multiplexing Guide

### ISSUE THREAD

**Issue by matwszedybyl** [smartdevicelink/sdl_android_guides#34]
In the Upgrading to Multiplexing Guide...

At the start of the guide, The "new" SdlService 's proxy instantiation is the one used in the Getting Started Guide, so the 'old' one doesn't exist and we dont have to change/update anything.

**Comment by joeygrover** [comment]
See comment on #35
