### ISSUE TITLE
Include version into gradle compile line

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android_guides#66]
Currently we have the line with a placeholder for version which forces the developer to look up a version and hardcod it into their gradle build file.

```xml
dependencies {
    compile 'com.smartdevicelink:sdl_android:{version}'
}
```

Instead we should add the current major version with `+` so that they are always building with the latest minor release. 

```xml
dependencies {
    compile 'com.smartdevicelink:sdl_android:4.+'
}
```

**Comment by brettywhite** [comment]
Merged in #67
