### ISSUE TITLE
Mobile Navigation Introduction - Broken Link

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android_guides#93]
In the `Connecting an app` section, there is a link to `Getting Started > Integration Basics` which directs to https://smartdevicelink.com/en/guides/android/mobile-navigation/introduction/Getting%20Started/Integration%20Basics/, showing a 404.  There is no longer an `Integration Basics` section in the guides, so I'm not sure where this link should go, but it should either be updated or removed.

**Comment by brettywhite** [comment]
closed with #15
